"""
Consumption vs Billing Reconciliation processor.

Reconciles one or more Consumption exports (XLSX) against one or more
Billing exports (CSV), matching on Sample ID plus a Parameter<->Assay Name
translation dictionary (see `_load_parameter_assay_match`), and produces a
5-sheet reconciliation workbook (Summary, Matched Items, Unbilled
Consumption, Unmatched Billing, Duplicate Items).

Only Parameters/Assay Names present in the configured
Parameter<->Assay Name mapping are considered at all - an item on either
side that has no counterpart in the mapping is outside the scope of this
reconciliation and never appears in any output sheet. This mirrors the
confirmed rule that the consumption tuple list is built "only for those
Parameter listed in parameter_assay_match", and is required for the
billing side regardless since a billing row's Assay Name must be
translatable to a Parameter before it can even be looked up.

FlowForge entrypoint: `process(input_files, form_data, output_dir)`.
"""
import json
import os
from datetime import datetime
from typing import Dict, List, Tuple, Union

import pandas as pd

from apps.processors.common import (
    build_output_filename,
    normalize_paths,
    read_and_concat_csvs,
    wrap_processing_errors,
)
from apps.settings.models import ApplicationSetting
from apps.workflows.services import ProcessingError

# ApplicationSetting key holding the Parameter<->Assay Name mapping, as a
# JSON string: a list of {"Parameter": "...", "Assay Name": "..."}
# objects. Stored here (rather than a file shipped with the processor) so
# a new organization's mapping can be edited in Django admin
# (Settings > Application Settings) without any code or file changes.
PARAMETER_ASSAY_MATCH_SETTING_KEY = 'CONSUMPTION_BILLING_PARAMETER_ASSAY_MATCH'

# Consumption export columns this processor needs. Only these two are
# kept - the algorithm operates on the (Sample ID, Parameter) tuple only.
CONSUMPTION_REQUIRED_COLUMNS = ['Sample_ID', 'Parameter']

# Billing export columns this processor needs, in addition to whatever
# else the export contains (every other billing column is preserved
# as-is and passed through to the Matched/Unmatched/Duplicate sheets).
BILLING_REQUIRED_COLUMNS = ['Sample_ID', 'Assay_Name']

# How many leading rows of a Consumption export to scan for the real
# header row. Real-world exports include a report-header block (title,
# date range, "Generated By" line, blank rows) above the actual column
# headers, and the number of such rows varies by organization/export
# template - so the offset is detected rather than hardcoded.
HEADER_SCAN_LIMIT = 50


def process(input_files: Dict[str, Union[str, List[str]]], form_data: dict, output_dir: str) -> dict:
    """
    Reconcile Consumption export(s) against Billing export(s).

    Args:
        input_files: Mapping of form field names to temp file path(s).
            Expected keys:
                - 'consumption_files': path or list of paths to
                  Consumption XLSX exports.
                - 'billing_files': path or list of paths to Billing CSV
                  exports.
        form_data: Any other form field values submitted with the
            workflow. An optional 'batch_label' key, if present and
            non-empty, is sanitized and included in the generated output
            filename.
        output_dir: Directory (already created by WorkflowProcessorService)
            that the generated report must be written into.

    Returns:
        A dict mapping the output key to the generated file path, e.g.
        {'reconciliation_report': '/path/to/output_dir/out_ConsumptionBillingRecon_Jul_2026.xlsx'}.

    Raises:
        ProcessingError: If required files or configuration are missing,
            malformed, or processing otherwise fails. Raised with a
            user-friendly message.
    """
    consumption_paths = normalize_paths(input_files.get('consumption_files'))
    billing_paths = normalize_paths(input_files.get('billing_files'))

    if not consumption_paths:
        raise ProcessingError('No Consumption files were uploaded.')
    if not billing_paths:
        raise ProcessingError('No Billing files were uploaded.')

    parameter_to_assay, assay_to_parameter = _load_parameter_assay_match()

    with wrap_processing_errors('Consumption vs Billing Reconciliation'):
        consumption_df = _load_consumption_files(consumption_paths)
        billing_df = _load_billing_files(billing_paths)

    if consumption_df.empty:
        raise ProcessingError('No consumption rows were found across the uploaded file(s).')
    if billing_df.empty:
        raise ProcessingError('No billing rows were found across the uploaded file(s).')

    with wrap_processing_errors('Consumption vs Billing Reconciliation'):
        results = _reconcile(consumption_df, billing_df, parameter_to_assay, assay_to_parameter)

    output_filename = build_output_filename(
        'ConsumptionBillingRecon', form_data, datetime.now(), extension='xlsx'
    )
    output_path = os.path.join(output_dir, output_filename)
    _write_workbook(results, output_path)

    return {'reconciliation_report': output_path}


def _load_parameter_assay_match() -> Tuple[Dict[str, str], Dict[str, str]]:
    """
    Load the Parameter<->Assay Name mapping from the
    `PARAMETER_ASSAY_MATCH_SETTING_KEY` ApplicationSetting.

    Returns:
        Tuple of (parameter_to_assay, assay_to_parameter) dicts. Matching
        is exact/byte-for-byte on both sides (no case-folding or
        whitespace-stripping) - confirmed against a real export where a
        Parameter value ("S.Sodium  ( NA )") contains a double space that
        must be preserved for the mapping to work.

    Raises:
        ProcessingError: If the setting is missing, not valid JSON, or
            contains no usable entries.
    """
    raw_value = ApplicationSetting.get_setting(PARAMETER_ASSAY_MATCH_SETTING_KEY, default=None)
    if not raw_value:
        raise ProcessingError(
            f"The '{PARAMETER_ASSAY_MATCH_SETTING_KEY}' application setting is not configured. "
            'Ask an administrator to add it under Settings > Application Settings, as a JSON '
            'list of {"Parameter": "...", "Assay Name": "..."} objects.'
        )

    try:
        entries = json.loads(raw_value)
    except (json.JSONDecodeError, TypeError) as exc:
        raise ProcessingError(
            f"The '{PARAMETER_ASSAY_MATCH_SETTING_KEY}' setting is not valid JSON: {exc}"
        )

    parameter_to_assay: Dict[str, str] = {}
    assay_to_parameter: Dict[str, str] = {}
    for entry in entries:
        parameter = entry.get('Parameter')
        assay = entry.get('Assay Name')
        if not parameter or not assay:
            continue
        # Last entry for a given Parameter/Assay Name wins if the
        # configured mapping has an accidental duplicate key - not
        # expected in practice, but documented rather than silently
        # raising, since a malformed mapping shouldn't crash the whole run.
        parameter_to_assay[parameter] = assay
        assay_to_parameter[assay] = parameter

    if not assay_to_parameter:
        raise ProcessingError(
            f"The '{PARAMETER_ASSAY_MATCH_SETTING_KEY}' setting contains no usable entries."
        )

    return parameter_to_assay, assay_to_parameter


def _find_header_row(raw: pd.DataFrame, required_columns: List[str]) -> int:
    """
    Scan the first `HEADER_SCAN_LIMIT` rows of a raw (header=None)
    DataFrame for the row containing all of `required_columns`
    (case-insensitive, whitespace-stripped) as cell values.

    Args:
        raw: The Consumption file read with header=None.
        required_columns: Column names that must all appear in the header
            row, e.g. ['Sample ID', 'Parameter'].

    Returns:
        The 0-indexed row position of the header row.

    Raises:
        ProcessingError: If no such row is found within the scan limit.
    """
    required_lower = {c.strip().lower() for c in required_columns}
    scan_limit = min(HEADER_SCAN_LIMIT, len(raw))
    for row_idx in range(scan_limit):
        row_values = {
            str(v).strip().lower() for v in raw.iloc[row_idx].tolist() if pd.notna(v)
        }
        if required_lower.issubset(row_values):
            return row_idx
    raise ProcessingError(
        f'Could not locate a header row containing {sorted(required_columns)} '
        f'within the first {scan_limit} rows of the Consumption file.'
    )


def _load_single_consumption_file(path: str) -> pd.DataFrame:
    """
    Read one Consumption XLSX export, locating its real header row
    (skipping any report-header block above it), and return only the
    Sample_ID/Parameter columns the reconciliation algorithm needs.

    Args:
        path: Path to a single Consumption XLSX file.

    Returns:
        A DataFrame with exactly ['Sample_ID', 'Parameter'] columns,
        Sample_ID cast to string (the export may otherwise read a
        numeric-looking Sample ID in as an int/float).

    Raises:
        ProcessingError: If the header row can't be located, contains
            duplicate column names, or required columns are absent.
    """
    raw = pd.read_excel(path, header=None)
    header_row = _find_header_row(raw, ['Sample ID', 'Parameter'])

    df = raw.iloc[header_row + 1:].copy()
    df.columns = [str(c).strip().replace(' ', '_') for c in raw.iloc[header_row].tolist()]
    df = df.reset_index(drop=True)

    if df.columns.duplicated().any():
        raise ProcessingError(
            f'Duplicate column headers detected in Consumption file {os.path.basename(path)}.'
        )

    missing = [col for col in CONSUMPTION_REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ProcessingError(
            f"Consumption file {os.path.basename(path)} is missing required columns: {', '.join(missing)}."
        )

    df = df[CONSUMPTION_REQUIRED_COLUMNS].copy()
    df['Sample_ID'] = df['Sample_ID'].astype(str).str.strip()
    return df


def _load_consumption_files(paths: List[str]) -> pd.DataFrame:
    """Read and concatenate every uploaded Consumption file."""
    frames = [_load_single_consumption_file(path) for path in paths]
    return pd.concat(frames, ignore_index=True)


def _load_billing_files(paths: List[str]) -> pd.DataFrame:
    """
    Read and concatenate every uploaded Billing CSV file via the shared
    `read_and_concat_csvs` helper (which already strips/underscores
    headers), then validate and normalize the columns this processor needs.

    Args:
        paths: CSV file paths to concatenate.

    Returns:
        The concatenated DataFrame with every original billing column
        preserved, plus Sample_ID cast to string.

    Raises:
        ProcessingError: If duplicate column headers are found, or
            required columns are absent.
    """
    df = read_and_concat_csvs(paths)

    if df.columns.duplicated().any():
        raise ProcessingError('Duplicate column headers detected in an uploaded Billing file.')

    missing = [col for col in BILLING_REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ProcessingError(f"Billing file(s) are missing required columns: {', '.join(missing)}.")

    df['Sample_ID'] = df['Sample_ID'].astype(str).str.strip()
    return df


def _reconcile(
    consumption_df: pd.DataFrame,
    billing_df: pd.DataFrame,
    parameter_to_assay: Dict[str, str],
    assay_to_parameter: Dict[str, str],
) -> Dict[str, pd.DataFrame]:
    """
    Run the full reconciliation: filter both sides to mapped items,
    detect duplicates, then match consumption tuples against billing rows.

    Matching is fully vectorized (no per-row Python loop) so it scales to
    100,000+ records:
        - Both sides are deduplicated on their natural key first, so each
          (Sample_ID, Parameter) consumption key and each
          (Sample_ID, Assay_Name) billing key occurs at most once in the
          "working" sets used for matching.
        - Each billing row's Assay_Name is translated to its Parameter,
          and only the *first* billing occurrence of any resulting
          translated key is eligible to match - since consumption has at
          most one available unit per key, any later occurrence of the
          same translated key can never be satisfied regardless of
          whether the first occurrence actually matched.

    Args:
        consumption_df: Combined Consumption data (Sample_ID, Parameter).
        billing_df: Combined Billing data (Sample_ID, Assay_Name, plus
            every other original billing column).
        parameter_to_assay: Parameter -> Assay Name mapping.
        assay_to_parameter: Assay Name -> Parameter mapping.

    Returns:
        Dict of DataFrames keyed by sheet: 'summary', 'matched',
        'unbilled_consumption', 'unmatched_billing', 'duplicates'.
    """
    # --- Filter both sides to items present in the configured mapping ---
    consumption_filtered = consumption_df[
        consumption_df['Parameter'].isin(parameter_to_assay)
    ].reset_index(drop=True)
    total_consumption_items = len(consumption_filtered)

    billing_filtered = billing_df[
        billing_df['Assay_Name'].isin(assay_to_parameter)
    ].reset_index(drop=True)

    # --- Consumption-side duplicates: identical (Sample_ID, Parameter),
    # across all uploaded consumption files combined ---
    consumption_dup_mask = consumption_filtered.duplicated(subset=['Sample_ID', 'Parameter'], keep=False)
    consumption_duplicates = (
        consumption_filtered[consumption_dup_mask]
        .sort_values(['Sample_ID', 'Parameter'], kind='stable')
        .reset_index(drop=True)
    )
    consumption_working = consumption_filtered.drop_duplicates(
        subset=['Sample_ID', 'Parameter'], keep='first'
    ).reset_index(drop=True)

    # --- Billing-side duplicates: identical (Sample_ID, Assay_Name) only -
    # other columns may differ and a pair is still a duplicate. Only the
    # first occurrence of a duplicated pair proceeds to matching; every
    # occurrence (first and duplicate alike) is recorded on the Duplicate
    # Items sheet. ---
    billing_dup_mask = billing_filtered.duplicated(subset=['Sample_ID', 'Assay_Name'], keep=False)
    billing_duplicates = (
        billing_filtered[billing_dup_mask]
        .sort_values(['Sample_ID', 'Assay_Name'], kind='stable')
        .reset_index(drop=True)
    )
    billing_working = billing_filtered.drop_duplicates(
        subset=['Sample_ID', 'Assay_Name'], keep='first'
    ).reset_index(drop=True)

    # --- Matching ---
    billing_working = billing_working.copy()
    billing_working['__parameter__'] = billing_working['Assay_Name'].map(assay_to_parameter)
    billing_working['__key__'] = list(zip(billing_working['Sample_ID'], billing_working['__parameter__']))
    billing_working['__occurrence__'] = billing_working.groupby('__key__').cumcount()

    consumption_working = consumption_working.copy()
    consumption_working['__key__'] = list(zip(consumption_working['Sample_ID'], consumption_working['Parameter']))
    available_keys = set(consumption_working['__key__'])

    is_matchable = (billing_working['__occurrence__'] == 0) & billing_working['__key__'].isin(available_keys)

    drop_cols = ['__parameter__', '__key__', '__occurrence__']
    matched_df = billing_working[is_matchable].drop(columns=drop_cols).reset_index(drop=True)
    unmatched_billing_df = billing_working[~is_matchable].drop(columns=drop_cols).reset_index(drop=True)

    matched_keys = set(billing_working.loc[is_matchable, '__key__'])
    unbilled_consumption_df = (
        consumption_working[~consumption_working['__key__'].isin(matched_keys)]
        .drop(columns='__key__')
        .reset_index(drop=True)
    )

    # --- Duplicate Items sheet: billing duplicates (full billing columns)
    # followed by consumption duplicates (Sample_ID/Parameter only) ---
    billing_duplicates = billing_duplicates.copy()
    billing_duplicates.insert(0, 'Duplicate_Source', 'Billing')
    consumption_duplicates = consumption_duplicates.copy()
    consumption_duplicates.insert(0, 'Duplicate_Source', 'Consumption')
    duplicates_df = pd.concat([billing_duplicates, consumption_duplicates], ignore_index=True, sort=False)

    summary_df = pd.DataFrame(
        [
            ('Total Consumption Items', total_consumption_items),
            ('Matched', len(matched_df)),
            ('Unbilled Consumption', len(unbilled_consumption_df)),
            ('Unmatched Billing', len(unmatched_billing_df)),
            ('Duplicate Billing', len(billing_duplicates)),
            ('Duplicate Consumption', len(consumption_duplicates)),
        ],
        columns=['Metric', 'Count'],
    )

    return {
        'summary': summary_df,
        'matched': matched_df,
        'unbilled_consumption': unbilled_consumption_df,
        'unmatched_billing': unmatched_billing_df,
        'duplicates': duplicates_df,
    }


def _write_workbook(results: Dict[str, pd.DataFrame], output_path: str) -> None:
    """
    Write the 5-sheet reconciliation workbook.

    Args:
        results: Dict of DataFrames as returned by `_reconcile`.
        output_path: Destination .xlsx path.
    """
    sheet_order = [
        ('summary', 'Summary'),
        ('matched', 'Matched Items'),
        ('unbilled_consumption', 'Unbilled Consumption'),
        ('unmatched_billing', 'Unmatched Billing'),
        ('duplicates', 'Duplicate Items'),
    ]
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        for key, sheet_name in sheet_order:
            results[key].to_excel(writer, sheet_name=sheet_name, index=False)