"""
MDRO (Multi-Drug Resistant Organism) Register processor.

Reads one or more "Report Register" microbiology export files (Sample ID,
Parameter, Result Value in long/tall format), aggregates rows by Sample
ID, and produces a wide antibiogram-style summary: one row per sample
with demographic/sample metadata, Gram stain/ZN Stain/KOH/Organism
results, and a MIC value per antibiotic column where that antibiotic was
tested.

FlowForge entrypoint: `process(input_files, form_data, output_dir)`.
"""
import os
import re
from typing import Dict, List, Optional

import pandas as pd

from apps.processors.common import (
    build_output_filename,
    normalize_paths,
    read_and_concat_excels,
    wrap_processing_errors,
)
from apps.workflows.services import ProcessingError

# The real table header starts several rows into the export (the rows
# above it are report metadata: title, date range filter, "Generated By",
# etc.). 0-indexed, matching pandas.read_excel's `header` argument.
HEADER_ROW = 6

# Raw Result Date/Time format, e.g. "21-08-2026 13:46".
RESULT_DATETIME_FORMAT = '%d-%m-%Y %H:%M'

# Internal (post header-cleaning, i.e. spaces -> underscores) column name
# -> output column label, for the fields taken as-is from each sample's
# first row. Sample_ID itself is handled separately (it's also the
# groupby key), and Sr_No is regenerated rather than carried through.
METADATA_FIELDS: Dict[str, str] = {
    'Sample_Date/Time': 'Sample Date/Time',
    'Patient_ID': 'Patient ID',
    'Patient_Name': 'Patient Name',
    'Gender': 'Gender',
    'Age': 'Age',
    'Phone_No': 'Phone No',
    'Address': 'Address',
    'Ward_(Sample_Collection)': 'Ward (Sample Collection)',
    'Report_Name': 'Report Name',
    'Result_Date/Time': 'Result Date/Time',
}

# Output column label -> keyword (case-insensitive "contains" match)
# against the Parameter column. Within a sample's rows, every Parameter
# matching the keyword is a candidate; the one with the latest
# Result Date/Time wins. Matches real-world column-name variants
# already, e.g. keyword 'n stain' matches both 'ZN Stain' and 'Z N Stain',
# and 'gram stain' matches 'Gram stain'/'Gram Stain'/'Gram Stains'.
PARAMETER_KEYWORDS: Dict[str, str] = {
    'Gram stain': 'gram stain',
    'ZN Stain': 'n stain',
    'KOH': 'koh',
    'Organism': 'organism',
}

# The Organism value indicating "no organism isolated" in this export
# format. When a sample's latest Organism result equals this, antibiotic/
# MIC extraction is skipped entirely for that sample (its row is still
# produced, just with every antibiotic column blank).
ORGANISM_NO_GROWTH_PLACEHOLDER = '-'

# Output antibiotic columns, in the exact order the reference MDRO
# register template uses. Each is "CODE-Full Antibiotic Name"; the part
# after the first '-' is what raw antibiotic names get normalized and
# matched against (see _normalize_antibiotic_name / ANTIBIOTIC_COLUMN_MAP).
ANTIBIOTIC_COLUMNS: List[str] = [
    'AB-Amphotericin B', 'AM-Ampicillin', 'AMC-Amoxicillin/Clavulanic Acid',
    'AN-Amikacin', 'ATM-Aztreonam', 'C-Chloramphenicol', 'CAS-Caspofungin',
    'CAZ-Ceftazidime', 'CIP-Ciprofloxacin', 'CM-Clindamycin', 'CRO-Ceftriaxone',
    'CS-Colistin', 'CT-Ceftolozane/Tazobactam', 'CTX-Cefotaxime', 'CXM-Cefuroxime',
    'CXMA-Cefuroxime Axetil', 'CZA-Ceftazidime/Avibactam', 'CZX-Ceftizoxime',
    'DAP-Daptomycin', 'DO-Doxycycline', 'E-Erythromycin', 'ESB-ESBL',
    'ETP-Ertapenem', 'FCT-Flucytosine', 'FEP-Cefepime', 'FLU-Fluconazole',
    'FOS-Fosfomycin', 'FOX-Cefoxitin', 'FT-Nitrofurantoin', 'GM-Gentamicin',
    'HLG-Gentamicin High Level (synergy)', 'ICR-Inducible Clindamycin Resistance',
    'IPM-Imipenem', 'LEV-Levofloxacin', 'LNZ-Linezolid', 'MCF-Micafungin',
    'MEM-Meropenem', 'MNO-Minocycline', 'MXF-Moxifloxacin', 'NET-Netilmicin',
    'OX1-Oxacillin', 'OXSF-Cefoxitin Screen', 'P-Benzylpenicillin',
    'PB-Polymyxin B', 'RA-Rifampicin', 'SAM-Ampicillin/Sulbactam',
    'SFP-Cefoperazone/Sulbactam', 'SXT-Trimethoprim/Sulfamethoxazole',
    'TE-Tetracycline', 'TEC-Teicoplanin', 'TGC-Tigecycline', 'TM-Tobramycin',
    'TZP-Piperacillin/Tazobactam', 'VA-Vancomycin', 'VRC-Voriconazole',
]

# Known raw antibiotic-name typos/variations seen in real exports that
# don't normalize-match their intended output column automatically.
# Keyed by the already-normalized (lowercased, non-alphanumerics
# stripped) raw name.
ANTIBIOTIC_NAME_OVERRIDES: Dict[str, str] = {
    'nitrofutation': 'FT-Nitrofurantoin',
}

# Final output column order.
OUTPUT_COLUMNS: List[str] = (
    ['Sr No', 'Sample ID']
    + list(METADATA_FIELDS.values())
    + list(PARAMETER_KEYWORDS.keys())
    + ANTIBIOTIC_COLUMNS
)


def _normalize_antibiotic_name(name: str) -> str:
    """
    Normalize a raw antibiotic name for matching against an output column.

    Lowercases and strips everything but letters and digits, so formatting
    differences like "Piperacillin/Tazobactam" vs "Piperacillin-Tazobactam"
    vs "Piperacillin Tazobactam" all normalize to the same key.

    Args:
        name: The raw antibiotic name as it appears in the export.

    Returns:
        The normalized name, or an empty string if name is falsy/blank
        (e.g. the "-" placeholder used for an untested antibiotic slot).
    """
    return re.sub(r'[^a-z0-9]', '', str(name).lower())


def _build_antibiotic_column_map(columns: List[str]) -> Dict[str, str]:
    """
    Build a normalized-antibiotic-name -> output column lookup from
    ANTIBIOTIC_COLUMNS.

    Args:
        columns: Output antibiotic column labels, each "CODE-Full Name".

    Returns:
        Dict mapping the normalized "Full Name" portion to the full
        column label, e.g. {'piperacillintazobactam':
        'TZP-Piperacillin/Tazobactam'}.
    """
    mapping = {}
    for column in columns:
        _, _, full_name = column.partition('-')
        mapping[_normalize_antibiotic_name(full_name)] = column
    return mapping


ANTIBIOTIC_COLUMN_MAP: Dict[str, str] = _build_antibiotic_column_map(ANTIBIOTIC_COLUMNS)


def process(input_files: Dict[str, object], form_data: dict, output_dir: str) -> dict:
    """
    Process one or more Report Register export files into an MDRO
    antibiogram-style summary, one row per Sample ID.

    Args:
        input_files: Mapping of form field names to temp file path(s).
            Expected key:
                - 'register_files': path or list of paths to Report
                  Register .xlsx exports.
        form_data: Any other form field values submitted with the workflow.
            An optional 'batch_label' key, if present and non-empty, is
            sanitized and included in the generated output filename.
        output_dir: Directory (already created by WorkflowProcessorService)
            that the generated report must be written into.

    Returns:
        A dict mapping the output key to the generated file path, e.g.
        {'mdro_report': '/path/to/output_dir/out_mdro_Aug_2026.xlsx'}.

    Raises:
        ProcessingError: If required files are missing, malformed, or
            processing otherwise fails. Raised with a user-friendly message.
    """
    file_paths = normalize_paths(input_files.get('register_files'))
    if not file_paths:
        raise ProcessingError('No Report Register files were uploaded.')

    with wrap_processing_errors('MDRO Register'):
        df = read_and_concat_excels(file_paths, header=HEADER_ROW)
        df['Sample_ID'] = df['Sample_ID'].astype(str)
        rows = _build_output_rows(df)

    if not rows:
        raise ProcessingError('No sample rows were found in the uploaded file(s).')

    result_df = pd.DataFrame(rows, columns=[c for c in OUTPUT_COLUMNS if c != 'Sr No'])
    result_df.insert(0, 'Sr No', range(1, len(result_df) + 1))

    with wrap_processing_errors('MDRO Register'):
        start_time = _earliest_sample_datetime(df)

    output_filename = build_output_filename('mdro', form_data, start_time, extension='xlsx')
    output_path = os.path.join(output_dir, output_filename)
    result_df.to_excel(output_path, index=False)

    return {'mdro_report': output_path}


def _earliest_sample_datetime(df: pd.DataFrame) -> pd.Timestamp:
    """
    Parse Sample_Date/Time across the whole uploaded batch and return the
    earliest value, used for the output filename's month/year portion.

    Args:
        df: The concatenated, cleaned input DataFrame (before grouping).

    Returns:
        The earliest parsed Sample_Date/Time as a pandas Timestamp.

    Raises:
        KeyError: If Sample_Date/Time isn't present (surfaced by the
            caller's wrap_processing_errors as a friendly ProcessingError).
    """
    parsed = pd.to_datetime(df['Sample_Date/Time'], format=RESULT_DATETIME_FORMAT)
    return parsed.min()


def _build_output_rows(df: pd.DataFrame) -> List[dict]:
    """
    Group the cleaned input DataFrame by Sample_ID and build one output
    row dict per sample.

    Args:
        df: The concatenated, cleaned input DataFrame with Sample_ID
            already cast to str.

    Returns:
        A list of row dicts, each keyed by output column label (matching
        OUTPUT_COLUMNS minus 'Sr No', which is assigned afterward).
    """
    return [
        _build_sample_row(sample_id, group)
        for sample_id, group in df.groupby('Sample_ID', sort=False)
    ]


def _build_sample_row(sample_id: str, group: pd.DataFrame) -> dict:
    """
    Build one output row for a single sample's group of rows.

    Args:
        sample_id: The Sample ID this group belongs to (already str).
        group: This sample's rows, in original file order (this order
            matters for the ANTIBIOTIC NAME/MIC pairing below - it is
            NOT the same ordering used for the "latest result" lookups).

    Returns:
        A dict keyed by output column label, with every antibiotic
        column defaulting to '' and populated only where that antibiotic
        was tested (and Organism isn't the "no growth" placeholder).
    """
    row: dict = {column: '' for column in ANTIBIOTIC_COLUMNS}
    row['Sample ID'] = sample_id

    first_row = group.iloc[0]
    for internal_col, output_label in METADATA_FIELDS.items():
        value = first_row.get(internal_col, '')
        row[output_label] = '' if pd.isna(value) else value

    group_by_result_time = _sort_by_result_datetime(group)
    for output_label, keyword in PARAMETER_KEYWORDS.items():
        row[output_label] = _latest_parameter_value(group_by_result_time, keyword)

    if row['Organism'].strip() == ORGANISM_NO_GROWTH_PLACEHOLDER:
        return row

    row.update(_extract_antibiotic_results(group))
    return row


def _sort_by_result_datetime(group: pd.DataFrame) -> pd.DataFrame:
    """
    Sort a sample's rows by parsed Result_Date/Time (ascending), for
    picking the "latest matching result" for Gram stain/ZN Stain/KOH/
    Organism.

    Args:
        group: This sample's rows, in original file order.

    Returns:
        The same rows sorted by parsed Result_Date/Time. Unparseable
        values sort first (oldest) rather than raising, so a single
        malformed timestamp doesn't fail the whole sample.
    """
    parsed = pd.to_datetime(group['Result_Date/Time'], format=RESULT_DATETIME_FORMAT, errors='coerce')
    return group.assign(_sort_key=parsed).sort_values('_sort_key', kind='stable')


def _latest_parameter_value(group_sorted: pd.DataFrame, keyword: str) -> str:
    """
    Find the latest (by Result_Date/Time) Result_Value among rows whose
    Parameter contains keyword (case-insensitive).

    Args:
        group_sorted: This sample's rows, sorted ascending by parsed
            Result_Date/Time (see _sort_by_result_datetime).
        keyword: Substring to match against Parameter, case-insensitively.

    Returns:
        The matching row's Result_Value as a stripped string, or '' if no
        row's Parameter matched.
    """
    matched = group_sorted[
        group_sorted['Parameter'].astype(str).str.contains(keyword, case=False, na=False)
    ]
    if matched.empty:
        return ''
    value = matched.iloc[-1]['Result_Value']
    return '' if pd.isna(value) else str(value).strip()


def _extract_antibiotic_results(group: pd.DataFrame) -> Dict[str, str]:
    """
    Scan a sample's rows in original file order for ANTIBIOTIC NAME rows
    immediately followed by a MIC row, and map each to its output
    antibiotic column.

    Original file order (not chronologically re-sorted) is required here,
    since the pairing relies on strict row adjacency as laid out in the
    export - a real ANTIBIOTIC NAME row is always immediately followed by
    its MIC row in every sample checked against this export format.

    Args:
        group: This sample's rows, in original file order.

    Returns:
        Dict mapping output antibiotic column label to MIC value, for
        every antibiotic that both had a real (non-placeholder) name and
        matched a known output column.
    """
    params = group['Parameter'].astype(str).str.strip().str.upper().tolist()
    values = group['Result_Value'].tolist()

    results: Dict[str, str] = {}
    for i in range(len(params) - 1):
        if 'ANTIBIOTIC' not in params[i] or 'MIC' not in params[i + 1]:
            continue
        antibiotic_name = '' if pd.isna(values[i]) else str(values[i]).strip()
        mic_value = '' if pd.isna(values[i + 1]) else str(values[i + 1]).strip()
        column = _resolve_antibiotic_column(antibiotic_name)
        if column:
            results[column] = mic_value
    return results


def _resolve_antibiotic_column(antibiotic_name: str) -> Optional[str]:
    """
    Resolve a raw antibiotic name to its output column label.

    Args:
        antibiotic_name: The raw antibiotic name from an ANTIBIOTIC NAME
            row's Result_Value (e.g. "Piperacillin/Tazobactam", or "-"
            for an untested slot).

    Returns:
        The matching output column label, or None if the name is blank/a
        placeholder or doesn't match any known antibiotic (including via
        ANTIBIOTIC_NAME_OVERRIDES).
    """
    normalized = _normalize_antibiotic_name(antibiotic_name)
    if not normalized:
        return None
    if normalized in ANTIBIOTIC_NAME_OVERRIDES:
        return ANTIBIOTIC_NAME_OVERRIDES[normalized]
    return ANTIBIOTIC_COLUMN_MAP.get(normalized)